version: '3'
services:
  db:
    platform: linux/amd64
    container_name: book-collection-app-db
    image: postgis/postgis:15-3.3
    ports:
      - "4001:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - 'postgres:/var/lib/postgresql/data'


volumes:
  postgres:
    driver: local
